"""app.py から HTML テンプレートを抽出し worker/src/template_str.py を生成する"""
import json
import re

APP_PY = "app.py"
OUTPUT = "worker/src/template_str.py"

def main():
    with open(APP_PY, "r", encoding="utf-8") as f:
        content = f.read()
    # HTML_TEMPLATE = """ ... """ を抽出（最初の """ から対応する """ まで）
    start = content.find('HTML_TEMPLATE = """')
    if start == -1:
        raise SystemExit("HTML_TEMPLATE not found")
    start += len('HTML_TEMPLATE = """')
    end = content.find('"""', start)
    if end == -1:
        raise SystemExit("Closing triple quote not found")
    template = content[start:end]
    # Jinja の変数をプレースホルダーに置換
    template = template.replace("{{ TAROT_IMAGE_URLS | tojson }}", "__TAROT_IMAGE_URLS_JSON__")
    # worker/src を確保
    import os
    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write("# Auto-generated by scripts/extract_template.py\n")
        f.write("HTML_TEMPLATE = ")
        f.write(repr(template))
        f.write("\n")
    print("Wrote", OUTPUT)

if __name__ == "__main__":
    main()
