"""app.py から HTML テンプレートを抽出し worker/src/template_str.py を生成する。
   {{ booking_url }} -> __BOOKING_URL__
   <script src="/static/app.js"></script> -> インライン化（static/app.js を埋め込み）
"""
import os

APP_PY = "app.py"
STATIC_JS = "static/app.js"
OUTPUT = "worker/src/template_str.py"

def main():
    with open(APP_PY, "r", encoding="utf-8") as f:
        content = f.read()
    start = content.find('HTML_TEMPLATE = """')
    if start == -1:
        raise SystemExit("HTML_TEMPLATE not found")
    start += len('HTML_TEMPLATE = """')
    end = content.find('"""', start)
    if end == -1:
        raise SystemExit("Closing triple quote not found")
    template = content[start:end]
    template = template.replace("{{ TAROT_IMAGE_URLS | tojson }}", "__TAROT_IMAGE_URLS_JSON__")
    template = template.replace("{{ booking_url }}", "__BOOKING_URL__")
    if os.path.isfile(STATIC_JS):
        with open(STATIC_JS, "r", encoding="utf-8") as f:
            js_content = f.read()
        template = template.replace('<script src="/static/app.js"></script>', "<script>\n" + js_content + "\n</script>")
    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write("# Auto-generated by scripts/extract_template.py\n")
        f.write("HTML_TEMPLATE = ")
        f.write(repr(template))
        f.write("\n")
    print("Wrote", OUTPUT)

if __name__ == "__main__":
    main()
